spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project2
    username: root
    password: root
    
  jpa:
#    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 3306

logging:
	level:
		'[com.example.lucilor]': debug