spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project2
    username: root
    password: Critical0112Role!

  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8080
